<?php

use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $currencies = array(
        array('short_name' =>'AFN' , 'name' => 'Afghani', 'symbol' => 'F' ),
        array('short_name' =>'ALL' , 'name' => 'Lek', 'symbol' => 'Lek' ),
        array('short_name' =>'ANG' , 'name' => 'Netherlands Antillian Guilder', 'symbol' => 'ƒ' ),
        array('short_name' =>'ARS' , 'name' => 'Argentine Peso', 'symbol' => '$' ),
        array('short_name' =>'AUD' , 'name' => 'Australian Dollar', 'symbol' => '$' ),
        array('short_name' =>'AWG' , 'name' => 'Aruban Guilder', 'symbol' => 'ƒ' ),
        array('short_name' =>'AZN' , 'name' => 'Azerbaijanian Manat', 'symbol' => 'ман' ),
        array('short_name' =>'BAM' , 'name' => 'Convertible Marks', 'symbol' => 'KM' ),
        array('short_name' =>'BBD' , 'name' => 'Barbados Dollar', 'symbol' => '$' ),
        array('short_name' =>'BGN' , 'name' => 'Bulgarian Lev', 'symbol' => 'лв' ),
        array('short_name' =>'BMD' , 'name' => 'Bermudian Dollar', 'symbol' => '$' ),
        array('short_name' =>'BND' , 'name' => 'Brunei Dollar', 'symbol' => '$' ),
        array('short_name' =>'BOB' , 'name' => 'BOV Boliviano Mvdol', 'symbol' => '$b' ),
        array('short_name' =>'BRL' , 'name' => 'Brazilian Real', 'symbol' => 'R$' ),
        array('short_name' =>'BSD' , 'name' => 'Bahamian Dollar', 'symbol' => '$' ),
        array('short_name' =>'BWP' , 'name' => 'Pula', 'symbol' => 'P' ),
        array('short_name' =>'BYR' , 'name' => 'Belarussian Ruble', 'symbol' => 'p.' ),
        array('short_name' =>'BZD' , 'name' => 'Belize Dollar', 'symbol' => 'BZ$' ),
        array('short_name' =>'CAD' , 'name' => 'Canadian Dollar', 'symbol' => '$' ),
        array('short_name' =>'CHF' , 'name' => 'Swiss Franc', 'symbol' => 'CHF' ),
        array('short_name' =>'CLP' , 'name' => 'CLF Chilean Peso Unidades de fomento', 'symbol' => '$' ),
        array('short_name' =>'CNY' , 'name' => 'Yuan Renminbi', 'symbol' => '¥' ),
        array('short_name' =>'COP' , 'name' => 'COU Colombian Peso Unidad de Valor Real', 'symbol' => '$' ),
        array('short_name' =>'CRC' , 'name' => 'Costa Rican Colon', 'symbol' => '₡' ),
        array('short_name' =>'CUP' , 'name' => 'CUC Cuban Peso Peso Convertible', 'symbol' => '₱' ),
        array('short_name' =>'CZK' , 'name' => 'Czech Koruna', 'symbol' => 'Kč' ),
        array('short_name' =>'DKK' , 'name' => 'Danish Krone', 'symbol' => 'kr' ),
        array('short_name' =>'DOP' , 'name' => 'Dominican Peso', 'symbol' => 'RD$' ),
        array('short_name' =>'EGP' , 'name' => 'Egyptian Pound', 'symbol' => '£' ),
        array('short_name' =>'EUR' , 'name' => 'Euro', 'symbol' => '€' ),
        array('short_name' =>'FJD' , 'name' => 'Fiji Dollar', 'symbol' => '$' ),
        array('short_name' =>'FKP' , 'name' => 'Falkland Islands Pound', 'symbol' => '£' ),
        array('short_name' =>'GBP' , 'name' => 'Pound Sterling', 'symbol' => '£' ),
        array('short_name' =>'GIP' , 'name' => 'Gibraltar Pound', 'symbol' => '£' ),
        array('short_name' =>'GTQ' , 'name' => 'Quetzal', 'symbol' => 'Q' ),
        array('short_name' =>'GYD' , 'name' => 'Guyana Dollar', 'symbol' => '$' ),
        array('short_name' =>'HKD' , 'name' => 'Hong Kong Dollar', 'symbol' => '$' ),
        array('short_name' =>'HNL' , 'name' => 'Lempira', 'symbol' => 'L' ),
        array('short_name' =>'HRK' , 'name' => 'Croatian Kuna', 'symbol' => 'kn' ),
        array('short_name' =>'HUF' , 'name' => 'Forint', 'symbol' => 'Ft' ),
        array('short_name' =>'IDR' , 'name' => 'Rupiah', 'symbol' => 'Rp' ),
        array('short_name' =>'ILS' , 'name' => 'New Israeli Sheqel', 'symbol' => '₪' ),
        array('short_name' =>'IRR' , 'name' => 'Iranian Rial', 'symbol' => '﷼' ),
        array('short_name' =>'ISK' , 'name' => 'Iceland Krona', 'symbol' => 'kr' ),
        array('short_name' =>'JMD' , 'name' => 'Jamaican Dollar', 'symbol' => 'J$' ),
        array('short_name' =>'JPY' , 'name' => 'Yen', 'symbol' => '¥' ),
        array('short_name' =>'KGS' , 'name' => 'Som', 'symbol' => 'лв' ),
        array('short_name' =>'KHR' , 'name' => 'Riel', 'symbol' => '៛' ),
        array('short_name' =>'KPW' , 'name' => 'North Korean Won', 'symbol' => '₩' ),
        array('short_name' =>'KRW' , 'name' => 'Won', 'symbol' => '₩' ),
        array('short_name' =>'KYD' , 'name' => 'Cayman Islands Dollar', 'symbol' => '$' ),
        array('short_name' =>'KZT' , 'name' => 'Tenge', 'symbol' => 'лв' ),
        array('short_name' =>'LAK' , 'name' => 'Kip', 'symbol' => '₭' ),
        array('short_name' =>'LBP' , 'name' => 'Lebanese Pound', 'symbol' => '£' ),
        array('short_name' =>'LKR' , 'name' => 'Sri Lanka Rupee', 'symbol' => '₨' ),
        array('short_name' =>'LRD' , 'name' => 'Liberian Dollar', 'symbol' => '$' ),
        array('short_name' =>'LTL' , 'name' => 'Lithuanian Litas', 'symbol' => 'Lt' ),
        array('short_name' =>'LVL' , 'name' => 'Latvian Lats', 'symbol' => 'Ls' ),
        array('short_name' =>'MKD' , 'name' => 'Denar', 'symbol' => 'ден' ),
        array('short_name' =>'MNT' , 'name' => 'Tugrik', 'symbol' => '₮' ),
        array('short_name' =>'MUR' , 'name' => 'Mauritius Rupee', 'symbol' => '₨' ),
        array('short_name' =>'MXN' , 'name' => 'MXV Mexican Peso Mexican Unidad de Inversion (UDI)', 'symbol' => '$' ),
        array('short_name' =>'MYR' , 'name' => 'Malaysian Ringgit', 'symbol' => 'RM' ),
        array('short_name' =>'MZN' , 'name' => 'Metical', 'symbol' => 'MT' ),
        array('short_name' =>'NGN' , 'name' => 'Naira', 'symbol' => '₦' ),
        array('short_name' =>'NIO' , 'name' => 'Cordoba Oro', 'symbol' => 'C$' ),
        array('short_name' =>'NOK' , 'name' => 'Norwegian Krone', 'symbol' => 'kr' ),
        array('short_name' =>'NPR' , 'name' => 'Nepalese Rupee', 'symbol' => '₨' ),
        array('short_name' =>'NZD' , 'name' => 'New Zealand Dollar', 'symbol' => '$' ),
        array('short_name' =>'OMR' , 'name' => 'Rial Omani', 'symbol' => '﷼' ),
        array('short_name' =>'PAB' , 'name' => 'USD Balboa US Dollar', 'symbol' => 'B/.' ),
        array('short_name' =>'PEN' , 'name' => 'Nuevo Sol', 'symbol' => 'S/.' ),
        array('short_name' =>'PHP' , 'name' => 'Philippine Peso', 'symbol' => 'Php' ),
        array('short_name' =>'PKR' , 'name' => 'Pakistan Rupee', 'symbol' => '₨' ),
        array('short_name' =>'PLN' , 'name' => 'Zloty', 'symbol' => 'zł' ),
        array('short_name' =>'PYG' , 'name' => 'Guarani', 'symbol' => 'Gs' ),
        array('short_name' =>'QAR' , 'name' => 'Qatari Rial', 'symbol' => '﷼' ),
        array('short_name' =>'RON' , 'name' => 'New Leu', 'symbol' => 'lei' ),
        array('short_name' =>'RSD' , 'name' => 'Serbian Dinar', 'symbol' => 'Дин.' ),
        array('short_name' =>'RUB' , 'name' => 'Russian Ruble', 'symbol' => 'руб' ),
        array('short_name' =>'SAR' , 'name' => 'Saudi Riyal', 'symbol' => '﷼' ),
        array('short_name' =>'SBD' , 'name' => 'Solomon Islands Dollar', 'symbol' => '$' ),
        array('short_name' =>'SCR' , 'name' => 'Seychelles Rupee', 'symbol' => '₨' ),
        array('short_name' =>'SEK' , 'name' => 'Swedish Krona', 'symbol' => 'kr' ),
        array('short_name' =>'SGD' , 'name' => 'Singapore Dollar', 'symbol' => '$' ),
        array('short_name' =>'SHP' , 'name' => 'Saint Helena Pound', 'symbol' => '£' ),
        array('short_name' =>'SOS' , 'name' => 'Somali Shilling', 'symbol' => 'S' ),
        array('short_name' =>'SRD' , 'name' => 'Surinam Dollar', 'symbol' => '$' ),
        array('short_name' =>'SVC' , 'name' => 'USD El Salvador Colon US Dollar', 'symbol' => '$' ),
        array('short_name' =>'SYP' , 'name' => 'Syrian Pound', 'symbol' => '£' ),
        array('short_name' =>'THB' , 'name' => 'Baht', 'symbol' => '฿' ),
        array('short_name' =>'TRY' , 'name' => 'Turkish Lira', 'symbol' => 'TL' ),
        array('short_name' =>'TTD' , 'name' => 'Trinidad and Tobago Dollar', 'symbol' => 'TT$' ),
        array('short_name' =>'TWD' , 'name' => 'New Taiwan Dollar', 'symbol' => 'NT$' ),
        array('short_name' =>'UAH' , 'name' => 'Hryvnia', 'symbol' => '₴' ),
        array('short_name' =>'USD' , 'name' => 'US Dollar', 'symbol' => '$' ),
        array('short_name' =>'UYU' , 'name' => 'UYI Peso Uruguayo Uruguay Peso en Unidades Indexadas', 'symbol' => '$U' ),
        array('short_name' =>'UZS' , 'name' => 'Uzbekistan Sum', 'symbol' => 'лв' ),
        array('short_name' =>'VEF' , 'name' => 'Bolivar Fuerte', 'symbol' => 'Bs' ),
        array('short_name' =>'VND' , 'name' => 'Dong', 'symbol' => '₫' ),
        array('short_name' =>'XCD' , 'name' => 'East Caribbean Dollar', 'symbol' => '$' ),
        array('short_name' =>'YER' , 'name' => 'Yemeni Rial', 'symbol' => '﷼' ),
        array('short_name' =>'ZAR' , 'name' => 'Rand', 'symbol' => 'R' ),
      );

      foreach($currencies as $currency){
        \App\Currency::firstOrCreate($currency);
      }

    }

}
